DATA_DIR : './../../GeneratedData/SegmentedData_Model'
model_save_dir : './SAVED_MODEL_DATA'
OP_DIR : './../../Model_Output'
RESULT_DIR  : './../../Model_Results'
MODEL_NAME : 'mead'
id_col : 'PanjivaRecordID'
prcess_dirs:
china_export:
  process: False
  emb_dims : 16
  num_neg_samples : 8
  id_col : 'PanjivaRecordID'
  learning_rate : 0.0025
  num_epochs: 50
  batchsize : 512
  show_loss_figure : False
  save_loss_figure : False

peru_export:
  process: False
  emb_dims : 12
  num_neg_samples : 8
  id_col : 'PanjivaRecordID'
  learning_rate : 0.0025
  num_epochs: 50
  batchsize : 512
  show_loss_figure : False
  save_loss_figure : True

us_import:
  process: False
  emb_dims : 16
  num_neg_samples : 8
  id_col : 'PanjivaRecordID'
  learning_rate : 0.0025
  num_epochs: 50
  batchsize : 512
  show_loss_figure : False
  save_loss_figure : False

china_import:
  process: True
  emb_dims : 12
  num_neg_samples : 8
  id_col : 'PanjivaRecordID'
  learning_rate : 0.0025
  num_epochs: 50
  batchsize : 512
  show_loss_figure : False
  save_loss_figure : False



