MODEL_RESULTS_LOC: './../../Model_Results'
COLLATED_MODEL_OP_FILE_NAME : 'collated_model_output.csv'
HDF_OUTPUT_LOC : './../../HDF_Output'
COMBINED_OP_FILE_NAME : 'combined_output.csv'
COMBINED_SCORES_wTEXT_OP_FILE  : 'combined_op_wTextFlags.csv'

TEXT_FLAG_LOC : './../../GeneratedData/HDF/TradeDataTextFlags'
text_flag_column_name : 'kw_flag'
id_column_name : 'PanjivaRecordID'
text_flag : 'Text_Keyword_Flag'
