'save_dir': './../../GeneratedData/SegmentedData_Model'
'inp_dir' : './../../GeneratedData/SegmentedData'
'us_import':
  'use_cols':
    - 'PanjivaRecordID'
    - 'ConsigneePanjivaID'
    - 'ShipperPanjivaID'
    - 'ShipmentOrigin'
    - 'ShipmentDestination'
    - 'hscode_6'
    - 'PortOfUnlading'
    - 'PortOfLading'
    - 'Carrier'
  'num_neg_samples': 8
  'column_value_filters':
    'Carrier':
      - '(Usa))'
  'num_neg_samples_ape': 3
  'low_freq_bound': 1
'peru_export':
  'use_cols':
    - 'PanjivaRecordID'
    - 'ShipmentDestination'
    - 'hscode_6'
    - 'ShipperPanjivaID'
    - 'PortOfUnladingUNLOCODE'
    - 'CustomsCode'
    - 'TransportMethod'
    - 'LocationCode'
  'num_neg_samples': 8
  'column_value_filters': False
  'low_freq_bound': 1
'china_import':
  'use_cols':
    - 'PanjivaRecordID'
    - 'ConsigneePanjivaID'
    - 'ShipmentOrigin'
    - 'Province'
    - 'CountryOfSale'
    - 'TransportMethod'
    - 'AdminRegion'
    - 'TradeType'
    - 'hscode_6'
  'num_neg_samples': 8
  'column_value_filters':
    'ShipmentOrigin':
      - 'Countries (reg.) un-known'
    'CountryOfSale':
      - 'Countries (reg.) un-known'
  'low_freq_bound': 1
'china_export':
  'use_cols':
    - 'PanjivaRecordID'
    - 'AdminRegion'
    - 'CountryOfSale'
    - 'hscode_6'
    - 'ShipmentDestination'
    - 'Province'
    - 'ShipperPanjivaID'
    - 'TradeType'
    - 'TransportMethod'
  'num_neg_samples': 8
  'column_value_filters': False
  'low_freq_bound': 1
