china_import:
  process: False
  'use_cols':
    - 'PanjivaRecordID'
    - 'ConsigneePanjivaID'
    - 'ShipmentOrigin'
    - 'Province'
    - 'CountryOfSale'
    - 'TransportMethod'
    - 'AdminRegion'
    - 'TradeType'
    - 'HSCode'
    - 'HSCodeKeywords'
china_export:
  process: False
  'use_cols':
    - 'PanjivaRecordID'
    - 'AdminRegion'
    - 'HSCode'
    - 'ShipmentDestination'
    - 'Province'
    - 'ShipperPanjivaID'
    - 'ShipperCountry'
    - 'TradeType'
    - 'TransportMethod'
    - 'HSCodeKeywords'
    - 'CountryOfSale'
us_import:
  process: False
  'use_cols':
    - 'PanjivaRecordID'
    - 'ConsigneePanjivaID'
    - 'ShipperCountry'
    - 'ShipperPanjivaID'
    - 'ShipmentOrigin'
    - 'ShipmentDestination'
    - 'HSCode'
    - 'PortOfUnlading'
    - 'PortOfLading'
    - 'Carrier'
    - 'GoodsShipped'
peru_export:
  process: False
  'use_cols':
    - 'PanjivaRecordID'
    - 'ShipmentDestination'
    - 'HSCode'
    - 'ShipperPanjivaID'
    - 'ShipperCountry'
    - 'PortOfUnladingUNLOCODE'
    - 'CustomsCode'
    - 'TransportMethod'
    - 'LocationCode'
    - 'GoodsShipped'
